name: demon-imaging-harmonisation
channels:
  - conda-forge
dependencies:
  - cmake
  - datalad=0.14.7
  - fsleyes=1.1.0
  - nipype=1.6.1
  - pandas=1.3.2
  - pip=21.2.4
  - python=3.7.10
  - requests=2.26.0
  - scikit-learn=0.24.2
  - pip:
    - neuroCombat
    - datalad-installer
    - pybids
