name: demon-imaging-harmonisation
channels:
  - conda-forge
dependencies:
  - cmake
  - datalad=0.14.7
  - nest-asyncio=1.5.1
  - nipype=1.6.1
  - openpyxl=3.0.7
  - pandas=1.3.2
  - pip=21.2.4
  - python=3.7.10
  - requests=2.26.0
  - statsmodel=0.12.2
  - pip:
    - neuroCombat
    - datalad-installer
    - pybids
